import type { MarketplaceListing } from '@/types/marketplace';

/**
 * Seeded marketplace listings for local development without a database.
 * ~50 entries across various categories, networks, and price ranges.
 */

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString();

export const seededMarketplaceListings: MarketplaceListing[] = [
  // ── AI Inference ──────────────────────────────────────────
  {
    id: 'mkt-001',
    resourceUrl: 'https://api.openrouter.ai/v1/chat/completions',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'OpenRouter GPT-5 Chat Completion',
    description: 'Proxied GPT-5 chat completions via OpenRouter with streaming support. Accepts OpenAI-compatible request bodies.',
    category: 'ai-inference',
    tags: ['gpt-5', 'openai', 'chat', 'streaming', 'llm'],
    descriptionConfidence: 0.95,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(2),
    price: { amount: '500000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.6,
    reviewCount: 23,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(30),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-002',
    resourceUrl: 'https://api.bytedance.com/seeddream/v4/generate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'ByteDance SeedDream v4 Image Generation',
    description: 'Generate high-quality images from text prompts using ByteDance SeedDream v4. Supports aspect ratios, styles, and negative prompts.',
    category: 'ai-inference',
    tags: ['image-generation', 'diffusion', 'bytedance', 'text-to-image'],
    descriptionConfidence: 0.92,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(1),
    price: { amount: '5000000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }, { name: 'payai', lastSeen: daysAgo(1) }],
    avgRating: 4.2,
    reviewCount: 8,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(14),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-003',
    resourceUrl: 'https://api.inference.net/v1/embeddings',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Text Embedding API (ada-003)',
    description: 'Generate 1536-dimensional text embeddings for semantic search, clustering, and classification tasks.',
    category: 'ai-inference',
    tags: ['embeddings', 'semantic-search', 'ada', 'vectors'],
    descriptionConfidence: 0.88,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(3),
    price: { amount: '2000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.8,
    reviewCount: 41,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(60),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-004',
    resourceUrl: 'https://api.whispercloud.io/v1/transcribe',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Whisper Cloud Speech-to-Text',
    description: 'Transcribe audio files up to 25MB using OpenAI Whisper large-v3. Supports 98 languages with automatic detection.',
    category: 'ai-inference',
    tags: ['speech-to-text', 'whisper', 'transcription', 'audio'],
    descriptionConfidence: 0.90,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(5),
    price: { amount: '100000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(1) }],
    avgRating: 4.4,
    reviewCount: 15,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(45),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mkt-005',
    resourceUrl: 'https://api.sentimentlab.ai/v2/analyze',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Sentiment Analysis API',
    description: 'Analyze text sentiment with fine-grained emotion detection. Returns confidence scores for positive, negative, neutral, and 8 specific emotions.',
    category: 'ai-inference',
    tags: ['sentiment', 'nlp', 'emotion-detection', 'text-analysis'],
    descriptionConfidence: 0.87,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(4),
    price: { amount: '800', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 3.9,
    reviewCount: 6,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(20),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(0),
  },

  // ── Finance ───────────────────────────────────────────────
  {
    id: 'mkt-006',
    resourceUrl: 'https://x402.aurelianflo.com/api/exchange-rates/USD',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Foreign Exchange Rate Conversion API',
    description: 'FX conversion quotes for a base currency with optional target list and amount. Query: ?to=EUR,GBP,JPY&amount=100.',
    category: 'finance',
    tags: ['forex', 'currency-conversion', 'exchange-rates', 'fx-quotes', 'real-time'],
    descriptionConfidence: 0.95,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '12000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }, { name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.1,
    reviewCount: 12,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(30),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-007',
    resourceUrl: 'https://api.stockpulse.io/v1/quote',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Real-Time Stock Quote',
    description: 'Get real-time stock quotes for US equities. Returns last price, change, volume, bid/ask, and market cap.',
    category: 'finance',
    tags: ['stocks', 'equities', 'quotes', 'market-data', 'real-time'],
    descriptionConfidence: 0.91,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(2),
    price: { amount: '5000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.3,
    reviewCount: 19,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(50),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-008',
    resourceUrl: 'https://api.bizday.io/v1/check',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Business Day Intelligence API',
    description: 'Check if a date is a business day, get next/previous business day, and calculate business day differences across 50+ countries.',
    category: 'finance',
    tags: ['business-days', 'calendar', 'holidays', 'scheduling'],
    descriptionConfidence: 0.93,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(3),
    price: { amount: '8000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.5,
    reviewCount: 7,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(25),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-009',
    resourceUrl: 'https://api.taxcalc.ai/v1/estimate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Tax Estimation Calculator',
    description: 'Estimate federal and state income tax for US taxpayers. Supports W-2, 1099, and capital gains scenarios.',
    category: 'finance',
    tags: ['tax', 'calculator', 'income-tax', 'us-tax'],
    descriptionConfidence: 0.85,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(6),
    price: { amount: '25000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(1) }],
    avgRating: 3.8,
    reviewCount: 4,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(15),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },

  // ── Web Scraping ──────────────────────────────────────────
  {
    id: 'mkt-010',
    resourceUrl: 'https://api.robotscheck.io/v1/parse',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Robots.txt Parser',
    description: 'Parse and analyze robots.txt files. Returns structured rules, sitemaps, crawl delays, and user-agent directives.',
    category: 'web-scraping',
    tags: ['robots-txt', 'seo', 'crawling', 'parser'],
    descriptionConfidence: 0.94,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '5000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.0,
    reviewCount: 9,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(35),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(35),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-011',
    resourceUrl: 'https://api.seometa.io/v1/extract',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'SEO Meta Extract',
    description: 'Extract meta tags, Open Graph data, Twitter cards, structured data, and canonical URLs from any webpage.',
    category: 'web-scraping',
    tags: ['seo', 'meta-tags', 'open-graph', 'structured-data'],
    descriptionConfidence: 0.92,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(2),
    price: { amount: '20000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }, { name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.2,
    reviewCount: 14,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(40),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-012',
    resourceUrl: 'https://api.deadlink.io/v1/check',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Dead Link Checker',
    description: 'Check a batch of URLs for dead links, redirects, and timeouts. Returns status codes and redirect chains.',
    category: 'web-scraping',
    tags: ['dead-links', 'link-checker', 'seo', 'health-check'],
    descriptionConfidence: 0.89,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(3),
    price: { amount: '50000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 3.7,
    reviewCount: 5,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(28),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-013',
    resourceUrl: 'https://api.websnap.io/v1/screenshot',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Website Screenshot API',
    description: 'Capture full-page or viewport screenshots of any URL. Supports custom dimensions, delays, and PDF export.',
    category: 'web-scraping',
    tags: ['screenshot', 'capture', 'headless-browser', 'pdf'],
    descriptionConfidence: 0.91,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(4),
    price: { amount: '75000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(1) }],
    avgRating: 4.1,
    reviewCount: 11,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(22),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(1),
  },

  // ── Crypto ────────────────────────────────────────────────
  {
    id: 'mkt-014',
    resourceUrl: 'https://api.chainguard.io/v1/address/check',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Malicious Address Detection',
    description: 'Check if a blockchain address has been flagged for scams, hacks, or sanctions across multiple databases.',
    category: 'crypto',
    tags: ['security', 'sanctions', 'fraud-detection', 'compliance'],
    descriptionConfidence: 0.93,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(1),
    price: { amount: '0', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.7,
    reviewCount: 31,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(55),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-015',
    resourceUrl: 'https://api.tokenswap.x402/v1/buy/FLASH',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Buy FLASH Tokens with USDC',
    description: 'Swap USDC for FLASH tokens on Base network. Includes slippage protection and MEV resistance.',
    category: 'crypto',
    tags: ['swap', 'defi', 'flash', 'base', 'tokens'],
    descriptionConfidence: 0.88,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(2),
    price: { amount: '5000000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 3.5,
    reviewCount: 3,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(10),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-016',
    resourceUrl: 'https://api.gaswatch.io/v1/estimate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Gas Price Estimator',
    description: 'Get current gas price estimates for Ethereum, Base, Arbitrum, and Optimism. Returns slow, standard, and fast tiers.',
    category: 'crypto',
    tags: ['gas', 'ethereum', 'l2', 'transaction-fees'],
    descriptionConfidence: 0.90,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(1),
    price: { amount: '500', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }, { name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.4,
    reviewCount: 18,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(42),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(42),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-017',
    resourceUrl: 'https://api.nftval.io/v1/floor',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'NFT Floor Price Lookup',
    description: 'Get floor prices for NFT collections on Ethereum and Solana. Includes 24h change, volume, and holder count.',
    category: 'crypto',
    tags: ['nft', 'floor-price', 'collections', 'market-data'],
    descriptionConfidence: 0.86,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(5),
    price: { amount: '3000', network: 'solana', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(1) }],
    avgRating: 3.6,
    reviewCount: 4,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(18),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(18),
    updatedAt: daysAgo(1),
  },

  // ── Weather ───────────────────────────────────────────────
  {
    id: 'mkt-018',
    resourceUrl: 'https://api.wxnow.io/v1/current',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Current Weather Conditions',
    description: 'Get current weather conditions by coordinates or city name. Returns temperature, humidity, wind, UV index, and air quality.',
    category: 'weather',
    tags: ['weather', 'current', 'temperature', 'air-quality'],
    descriptionConfidence: 0.94,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(1),
    price: { amount: '1000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.6,
    reviewCount: 28,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(65),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(65),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-019',
    resourceUrl: 'https://api.wxnow.io/v1/forecast',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: '7-Day Weather Forecast',
    description: 'Get 7-day hourly and daily weather forecasts. Includes precipitation probability, wind gusts, and severe weather alerts.',
    category: 'weather',
    tags: ['weather', 'forecast', 'alerts', 'precipitation'],
    descriptionConfidence: 0.93,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(1),
    price: { amount: '3500', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.5,
    reviewCount: 22,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(65),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(65),
    updatedAt: daysAgo(0),
  },

  // ── Data Lookup ───────────────────────────────────────────
  {
    id: 'mkt-020',
    resourceUrl: 'https://api.ipgeo.io/v1/lookup',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'IP Geolocation Lookup',
    description: 'Get geographic location, ISP, ASN, and threat assessment for any IPv4 or IPv6 address.',
    category: 'data-lookup',
    tags: ['ip', 'geolocation', 'isp', 'asn', 'threat-intel'],
    descriptionConfidence: 0.92,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(2),
    price: { amount: '1500', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.3,
    reviewCount: 16,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(48),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(48),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-021',
    resourceUrl: 'https://api.whodat.io/v1/whois',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'WHOIS Domain Lookup',
    description: 'Query WHOIS data for domain registration, expiration dates, registrar info, and nameservers.',
    category: 'data-lookup',
    tags: ['whois', 'domain', 'registrar', 'dns'],
    descriptionConfidence: 0.91,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(3),
    price: { amount: '8000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.0,
    reviewCount: 10,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(33),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(33),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-022',
    resourceUrl: 'https://api.companyinfo.io/v1/profile',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Company Profile Lookup',
    description: 'Retrieve company details including industry, employee count, funding rounds, and key personnel by domain or company name.',
    category: 'data-lookup',
    tags: ['company', 'business-intelligence', 'firmographics', 'crm'],
    descriptionConfidence: 0.87,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(5),
    price: { amount: '35000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(1) }],
    avgRating: 3.9,
    reviewCount: 6,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(20),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mkt-023',
    resourceUrl: 'https://api.phoneverify.io/v1/validate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Phone Number Validation',
    description: 'Validate and format phone numbers globally. Returns carrier, line type, country, and whether the number is reachable.',
    category: 'data-lookup',
    tags: ['phone', 'validation', 'carrier', 'telecom'],
    descriptionConfidence: 0.90,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(4),
    price: { amount: '4000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.2,
    reviewCount: 13,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(38),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(38),
    updatedAt: daysAgo(0),
  },

  // ── Search ────────────────────────────────────────────────
  {
    id: 'mkt-024',
    resourceUrl: 'https://api.surfresearch.io/v1/search',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Surf Research Deep Search',
    description: 'AI-powered deep web search that returns structured summaries with source citations. Supports follow-up questions.',
    category: 'search',
    tags: ['search', 'ai-search', 'research', 'citations'],
    descriptionConfidence: 0.88,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(2),
    price: { amount: '2000000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.4,
    reviewCount: 17,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(12),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-025',
    resourceUrl: 'https://api.patentsearch.io/v1/query',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Patent Search API',
    description: 'Search US and international patent databases by keyword, assignee, inventor, or classification code.',
    category: 'search',
    tags: ['patents', 'intellectual-property', 'legal-research'],
    descriptionConfidence: 0.85,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(6),
    price: { amount: '15000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(2) }],
    avgRating: 3.8,
    reviewCount: 3,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(16),
    lastSeenAt: daysAgo(2),
    createdAt: daysAgo(16),
    updatedAt: daysAgo(2),
  },

  // ── Compute ───────────────────────────────────────────────
  {
    id: 'mkt-026',
    resourceUrl: 'https://api.mathcloud.io/v1/fibonacci',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Fibonacci Number Generator',
    description: 'Compute Fibonacci numbers up to n=10000. Returns the number, computation time, and digit count.',
    category: 'compute',
    tags: ['math', 'fibonacci', 'computation', 'numbers'],
    descriptionConfidence: 0.96,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '1000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.9,
    reviewCount: 2,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(30),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-027',
    resourceUrl: 'https://api.coderun.io/v1/execute',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Sandboxed Code Execution',
    description: 'Execute Python, JavaScript, or Go code in an isolated sandbox. 30s timeout, 256MB memory limit, network disabled.',
    category: 'compute',
    tags: ['sandbox', 'code-execution', 'python', 'javascript', 'go'],
    descriptionConfidence: 0.89,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(3),
    price: { amount: '150000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.1,
    reviewCount: 9,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(25),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-028',
    resourceUrl: 'https://api.pdfparse.io/v1/extract',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'PDF Text Extraction',
    description: 'Extract text, tables, and metadata from PDF files up to 50MB. Supports OCR for scanned documents.',
    category: 'compute',
    tags: ['pdf', 'ocr', 'text-extraction', 'document-processing'],
    descriptionConfidence: 0.91,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(2),
    price: { amount: '30000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.3,
    reviewCount: 20,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(52),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(52),
    updatedAt: daysAgo(0),
  },

  // ── Social ────────────────────────────────────────────────
  {
    id: 'mkt-029',
    resourceUrl: 'https://api.xfetch.io/v1/user/profile',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'X/Twitter User Profile Lookup',
    description: 'Fetch public profile data for any X/Twitter user. Returns bio, follower counts, verification status, and pinned tweet.',
    category: 'social',
    tags: ['twitter', 'x', 'profile', 'social-media'],
    descriptionConfidence: 0.92,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(1),
    price: { amount: '0', network: 'solana', decimals: 6 },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 3.4,
    reviewCount: 7,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(8),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-030',
    resourceUrl: 'https://api.xfetch.io/v1/user/timeline',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'X/Twitter User Timeline',
    description: 'Fetch recent tweets from a user timeline. Returns up to 100 tweets with engagement metrics and media attachments.',
    category: 'social',
    tags: ['twitter', 'x', 'timeline', 'tweets'],
    descriptionConfidence: 0.91,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(1),
    price: { amount: '0', network: 'solana', decimals: 6 },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 3.2,
    reviewCount: 5,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(8),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-031',
    resourceUrl: 'https://api.redditpulse.io/v1/subreddit/hot',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Reddit Subreddit Hot Posts',
    description: 'Get the top hot posts from any public subreddit. Returns titles, scores, comment counts, and content previews.',
    category: 'social',
    tags: ['reddit', 'subreddit', 'hot-posts', 'social-media'],
    descriptionConfidence: 0.88,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(4),
    price: { amount: '2500', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.0,
    reviewCount: 8,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(19),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(19),
    updatedAt: daysAgo(0),
  },

  // ── Security ──────────────────────────────────────────────
  {
    id: 'mkt-032',
    resourceUrl: 'https://api.secheaders.io/v1/analyze',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Security Headers Analyzer',
    description: 'Analyze HTTP security headers for any URL. Grades CSP, HSTS, X-Frame-Options, and more with remediation advice.',
    category: 'security',
    tags: ['security-headers', 'csp', 'hsts', 'vulnerability-assessment'],
    descriptionConfidence: 0.93,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '10000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.5,
    reviewCount: 14,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(40),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-033',
    resourceUrl: 'https://api.sslcheck.io/v1/certificate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'SSL Certificate Checker',
    description: 'Check SSL/TLS certificate validity, expiration, chain completeness, and protocol support for any hostname.',
    category: 'security',
    tags: ['ssl', 'tls', 'certificate', 'https', 'expiration'],
    descriptionConfidence: 0.94,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(2),
    price: { amount: '10000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }, { name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.6,
    reviewCount: 21,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(50),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-034',
    resourceUrl: 'https://api.vulnscan.io/v1/scan',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Vulnerability Scanner',
    description: 'Scan a URL or IP for common vulnerabilities including outdated software, open ports, and misconfigurations.',
    category: 'security',
    tags: ['vulnerability', 'scanning', 'pentest', 'security-audit'],
    descriptionConfidence: 0.86,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(5),
    price: { amount: '200000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(1) }],
    avgRating: 3.7,
    reviewCount: 4,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(14),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
  },

  // ── Legal ─────────────────────────────────────────────────
  {
    id: 'mkt-035',
    resourceUrl: 'https://api.contractparse.io/v1/analyze',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Contract Clause Analyzer',
    description: 'Analyze legal contracts to extract key clauses, obligations, termination conditions, and risk factors.',
    category: 'legal',
    tags: ['contract', 'legal-analysis', 'clauses', 'risk-assessment'],
    descriptionConfidence: 0.84,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(7),
    price: { amount: '500000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(2) }],
    avgRating: 3.6,
    reviewCount: 2,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(10),
    lastSeenAt: daysAgo(2),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: 'mkt-036',
    resourceUrl: 'https://api.toscheck.io/v1/summarize',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Terms of Service Summarizer',
    description: 'Summarize Terms of Service documents with plain-language highlights of key rights, restrictions, and data practices.',
    category: 'legal',
    tags: ['tos', 'privacy-policy', 'summary', 'compliance'],
    descriptionConfidence: 0.83,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(8),
    price: { amount: '100000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(3) }],
    avgRating: 3.5,
    reviewCount: 1,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(8),
    lastSeenAt: daysAgo(3),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
  },

  // ── Dev Tools ─────────────────────────────────────────────
  {
    id: 'mkt-037',
    resourceUrl: 'https://api.jsonformat.io/v1/validate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'JSON Schema Validator',
    description: 'Validate JSON documents against JSON Schema (draft-07/2019-09/2020-12). Returns detailed error paths and messages.',
    category: 'devtools',
    tags: ['json', 'schema', 'validation', 'api-testing'],
    descriptionConfidence: 0.95,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '200', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.7,
    reviewCount: 25,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(58),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(58),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-038',
    resourceUrl: 'https://api.regextest.io/v1/match',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Regex Pattern Tester',
    description: 'Test regex patterns against input strings. Returns matches, capture groups, and performance metrics. Supports PCRE2 and RE2.',
    category: 'devtools',
    tags: ['regex', 'pattern-matching', 'testing', 'pcre'],
    descriptionConfidence: 0.93,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(2),
    price: { amount: '100', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.8,
    reviewCount: 33,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(62),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(62),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-039',
    resourceUrl: 'https://api.diffmerge.io/v1/diff',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Text Diff & Merge API',
    description: 'Compute unified diffs between two text inputs. Supports three-way merge, word-level diffs, and patch generation.',
    category: 'devtools',
    tags: ['diff', 'merge', 'text-comparison', 'patch'],
    descriptionConfidence: 0.90,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(3),
    price: { amount: '500', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.4,
    reviewCount: 12,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(30),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-040',
    resourceUrl: 'https://api.crontranslate.io/v1/parse',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Cron Expression Parser',
    description: 'Parse cron expressions into human-readable descriptions. Returns next 10 execution times and validates syntax.',
    category: 'devtools',
    tags: ['cron', 'scheduling', 'parser', 'time'],
    descriptionConfidence: 0.94,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(2),
    price: { amount: '50', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.9,
    reviewCount: 15,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(45),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(0),
  },

  // ── MCP Tools ─────────────────────────────────────────────
  {
    id: 'mkt-041',
    resourceUrl: 'mcp://github-copilot-agent/code-review',
    type: 'mcp',
    x402Version: 2,
    mcpToolName: 'review_pull_request',
    title: 'AI Code Review (MCP)',
    description: 'Automated pull request review via MCP. Analyzes code quality, security issues, performance, and provides inline suggestions.',
    category: 'devtools',
    tags: ['code-review', 'mcp', 'pull-request', 'ai'],
    descriptionConfidence: 0.87,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(4),
    price: { amount: '250000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(1) }],
    avgRating: 4.0,
    reviewCount: 6,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(12),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mkt-042',
    resourceUrl: 'mcp://db-query-agent/natural-language-sql',
    type: 'mcp',
    x402Version: 2,
    mcpToolName: 'query_database',
    title: 'Natural Language SQL Query (MCP)',
    description: 'Convert natural language questions into SQL queries and execute them against your database. Supports PostgreSQL, MySQL, and SQLite.',
    category: 'compute',
    tags: ['sql', 'natural-language', 'database', 'mcp'],
    descriptionConfidence: 0.85,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(5),
    price: { amount: '50000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(2) }],
    avgRating: 3.8,
    reviewCount: 4,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(9),
    lastSeenAt: daysAgo(2),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(2),
  },

  // ── More varied price points ──────────────────────────────
  {
    id: 'mkt-043',
    resourceUrl: 'https://api.hashgen.io/v1/generate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Cryptographic Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512, and BLAKE3 hashes for text or file content.',
    category: 'devtools',
    tags: ['hash', 'cryptography', 'sha256', 'blake3'],
    descriptionConfidence: 0.96,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '25', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.9,
    reviewCount: 42,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(70),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(70),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-044',
    resourceUrl: 'https://api.uuidgen.io/v1/generate',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'UUID Generator',
    description: 'Generate UUIDs (v4, v7) and ULIDs in batch. Returns up to 1000 IDs per request.',
    category: 'devtools',
    tags: ['uuid', 'ulid', 'identifier', 'generator'],
    descriptionConfidence: 0.97,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '10', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 5.0,
    reviewCount: 3,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(55),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-045',
    resourceUrl: 'https://api.pinata.cloud/v1/file/private',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Pinata Private File Retrieval',
    description: 'Retrieve private files stored on IPFS via Pinata. Supports range requests and content type detection.',
    category: 'compute',
    tags: ['ipfs', 'pinata', 'file-storage', 'decentralized'],
    descriptionConfidence: 0.89,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(3),
    price: { amount: '100', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.1,
    reviewCount: 7,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(35),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(35),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-046',
    resourceUrl: 'https://api.creditspack.io/v1/purchase',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Purchase 500 Credits Package',
    description: 'Buy a 500-credit bundle for use across partnered x402 services. Credits do not expire.',
    category: 'other',
    tags: ['credits', 'bundle', 'package', 'prepaid'],
    descriptionConfidence: 0.82,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(5),
    price: { amount: '19000000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(1) }],
    avgRating: 0,
    reviewCount: 0,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(7),
    lastSeenAt: daysAgo(1),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: 'mkt-047',
    resourceUrl: 'https://api.gigabrain.trade/v1/signal',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'GigaBrain Crypto Trading Signal',
    description: 'AI-powered crypto trading signals based on on-chain analysis, social sentiment, and market microstructure.',
    category: 'crypto',
    tags: ['trading', 'signals', 'ai', 'on-chain', 'defi'],
    descriptionConfidence: 0.84,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(4),
    price: { amount: '500000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 3.3,
    reviewCount: 11,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(15),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(15),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-048',
    resourceUrl: 'https://api.solanawatch.io/v1/gpt5-agent',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Solana GPT-5 LLM Agent API',
    description: 'Run GPT-5 powered agent tasks on Solana blockchain data. Analyze transactions, decode programs, and trace token flows.',
    category: 'crypto',
    tags: ['solana', 'gpt-5', 'agent', 'blockchain-analysis'],
    descriptionConfidence: 0.81,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(6),
    price: { amount: '0', network: 'solana', decimals: 6 },
    facilitators: [{ name: 'payai', lastSeen: daysAgo(2) }],
    avgRating: 0,
    reviewCount: 0,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(5),
    lastSeenAt: daysAgo(2),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'mkt-049',
    resourceUrl: 'https://api.emailverify.io/v1/check',
    type: 'http',
    x402Version: 2,
    httpMethod: 'GET',
    title: 'Email Address Verifier',
    description: 'Verify email addresses for deliverability. Checks MX records, SMTP connection, disposable domains, and catch-all detection.',
    category: 'data-lookup',
    tags: ['email', 'verification', 'deliverability', 'smtp'],
    descriptionConfidence: 0.91,
    enrichmentSource: 'ai',
    enrichedAt: daysAgo(2),
    price: { amount: '6000', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }, { name: 'payai', lastSeen: daysAgo(0) }],
    avgRating: 4.4,
    reviewCount: 18,
    isVerified: true,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(44),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(44),
    updatedAt: daysAgo(0),
  },
  {
    id: 'mkt-050',
    resourceUrl: 'https://api.markdownlint.io/v1/check',
    type: 'http',
    x402Version: 2,
    httpMethod: 'POST',
    title: 'Markdown Lint & Format',
    description: 'Lint and auto-format Markdown documents. Checks headings, links, code blocks, and returns formatted output.',
    category: 'devtools',
    tags: ['markdown', 'lint', 'formatting', 'documentation'],
    descriptionConfidence: 0.93,
    enrichmentSource: 'raw',
    enrichedAt: daysAgo(1),
    price: { amount: '75', network: 'base', decimals: 6, tokenName: 'USD Coin' },
    facilitators: [{ name: 'coinbase', lastSeen: daysAgo(0) }],
    avgRating: 4.6,
    reviewCount: 10,
    isVerified: false,
    isStale: false,
    isTestnet: false,
    firstSeenAt: daysAgo(38),
    lastSeenAt: daysAgo(0),
    createdAt: daysAgo(38),
    updatedAt: daysAgo(0),
  },
];

// ────────────────────────────────────────────────────────────
// Helpers for the seeded marketplace (no-DB mode)
// ────────────────────────────────────────────────────────────

export function getSeededMarketplaceListings(params: {
  q?: string;
  category?: string;
  type?: string;
  network?: string;
  minRating?: number;
  maxPrice?: string;
  sort?: string;
  limit?: number;
  offset?: number;
}): { listings: MarketplaceListing[]; total: number } {
  let filtered = [...seededMarketplaceListings];

  // Text search
  if (params.q) {
    const q = params.q.toLowerCase();
    filtered = filtered.filter(
      (l) =>
        (l.title ?? '').toLowerCase().includes(q) ||
        (l.description ?? '').toLowerCase().includes(q) ||
        l.tags.some((t) => t.toLowerCase().includes(q)),
    );
  }

  // Category filter
  if (params.category) {
    filtered = filtered.filter((l) => l.category === params.category);
  }

  // Type filter
  if (params.type) {
    filtered = filtered.filter((l) => l.type === params.type);
  }

  // Network filter
  if (params.network) {
    filtered = filtered.filter((l) => l.price.network === params.network);
  }

  // Min rating filter
  if (params.minRating !== undefined) {
    filtered = filtered.filter((l) => l.avgRating >= params.minRating!);
  }

  // Max price filter
  if (params.maxPrice) {
    const maxPriceNum = Number(params.maxPrice);
    if (Number.isFinite(maxPriceNum)) {
      filtered = filtered.filter((l) => Number(l.price.amount) <= maxPriceNum);
    }
  }

  // Sort
  const priceValue = (l: MarketplaceListing) => {
    const amt = Number(l.price.amount || '0');
    return isNaN(amt) ? 0 : amt / Math.pow(10, l.price.decimals);
  };

  switch (params.sort) {
    case 'rating':
      filtered.sort((a, b) => b.avgRating - a.avgRating || b.reviewCount - a.reviewCount);
      break;
    case 'price_asc':
      filtered.sort((a, b) => priceValue(a) - priceValue(b));
      break;
    case 'price_desc':
      filtered.sort((a, b) => priceValue(b) - priceValue(a));
      break;
    case 'recent':
      filtered.sort((a, b) => new Date(b.lastSeenAt).getTime() - new Date(a.lastSeenAt).getTime());
      break;
    default:
      filtered.sort((a, b) => b.descriptionConfidence - a.descriptionConfidence);
      break;
  }

  const total = filtered.length;
  const offset = params.offset ?? 0;
  const limit = params.limit ?? 25;
  const listings = filtered.slice(offset, offset + limit);

  return { listings, total };
}

export function getSeededMarketplaceListing(id: string): MarketplaceListing | null {
  return seededMarketplaceListings.find((l) => l.id === id) ?? null;
}

export function getSeededMarketplaceFacets() {
  const listings = seededMarketplaceListings;

  const categoryMap = new Map<string, number>();
  const networkMap = new Map<string, number>();
  const typeMap = new Map<string, number>();

  for (const l of listings) {
    if (l.category) categoryMap.set(l.category, (categoryMap.get(l.category) ?? 0) + 1);
    networkMap.set(l.price.network, (networkMap.get(l.price.network) ?? 0) + 1);
    typeMap.set(l.type, (typeMap.get(l.type) ?? 0) + 1);
  }

  return {
    categories: Array.from(categoryMap.entries())
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count),
    networks: Array.from(networkMap.entries())
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count),
    types: Array.from(typeMap.entries())
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count),
    totalListings: listings.length,
    totalActive: listings.length,
  };
}
